// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZNhl6pIxUbX82HZ2l5UjP9M7FOa6Jf6Q',
    appId: '1:63439552189:android:b3cbe5174adf6e95dec1d4',
    messagingSenderId: '63439552189',
    projectId: 'ditonton-262cc',
    storageBucket: 'ditonton-262cc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOha-Zrdjlhqn03aOmsL7QelZE3R6V2T0',
    appId: '1:63439552189:ios:e3728af2bafdc013dec1d4',
    messagingSenderId: '63439552189',
    projectId: 'ditonton-262cc',
    storageBucket: 'ditonton-262cc.appspot.com',
    iosClientId: '63439552189-ev7i4cnkm1f95u17hj3e370idsrfmbd8.apps.googleusercontent.com',
    iosBundleId: 'com.dawam.ditonton',
  );
}
